//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bebbs.Harmonize.With.Harmony.Tests.Hub.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bebbs.Harmonize.With.Harmony.Tests.Hub.Configuration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;activity&quot;:[{&quot;suggestedDisplay&quot;:&quot;Default&quot;,&quot;label&quot;:&quot;PowerOff&quot;,&quot;id&quot;:&quot;-1&quot;,&quot;activityTypeDisplayName&quot;:&quot;Default&quot;,&quot;controlGroup&quot;:[],&quot;fixit&quot;:{&quot;15666630&quot;:{&quot;id&quot;:&quot;15666630&quot;,&quot;Power&quot;:&quot;Off&quot;}},&quot;sequences&quot;:[],&quot;icon&quot;:&quot;Default&quot;,&quot;type&quot;:&quot;PowerOff&quot;}],&quot;device&quot;:[{&quot;type&quot;:&quot;Amplifier&quot;,&quot;deviceTypeDisplayName&quot;:&quot;Amplifier&quot;,&quot;label&quot;:&quot;Yamaha Amp&quot;,&quot;id&quot;:&quot;15666630&quot;,&quot;Transport&quot;:1,&quot;controlGroup&quot;:[{&quot;name&quot;:&quot;Power&quot;,&quot;function&quot;:[{&quot;action&quot;:&quot;{\&quot;command\&quot;:\&quot;PowerOff\&quot;,\&quot;type\&quot;:\&quot;IRCommand\&quot;,\&quot;deviceId\&quot;:\&quot;15666630\&quot;}&quot;,&quot;name&quot;:&quot;PowerOff&quot;,&quot;label&quot;:&quot;Power [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleConfiguration {
            get {
                return ResourceManager.GetString("SimpleConfiguration", resourceCulture);
            }
        }
    }
}
