//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Bebbs.Harmonize.With.Messaging.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bebbs.co.uk/Harmonize/Messages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bebbs.co.uk/Harmonize/Messages", IsNullable=false)]
    public partial class Message {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Act", typeof(Act))]
        [System.Xml.Serialization.XmlElementAttribute("Deregister", typeof(Deregister))]
        [System.Xml.Serialization.XmlElementAttribute("Observation", typeof(Observation))]
        [System.Xml.Serialization.XmlElementAttribute("Observe", typeof(Observe))]
        [System.Xml.Serialization.XmlElementAttribute("Register", typeof(Register))]
        [System.Xml.Serialization.XmlElementAttribute("Subscribe", typeof(Subscribe))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Messages")]
    public partial class Act {
        
        private UniqueIdentifier entityField;
        
        private UniqueIdentifier actionableField;
        
        private UniqueIdentifier actorField;
        
        private ParameterValue[] parameterValuesField;
        
        /// <remarks/>
        public UniqueIdentifier Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Actionable {
            get {
                return this.actionableField;
            }
            set {
                this.actionableField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types", IsNullable=false)]
        public ParameterValue[] ParameterValues {
            get {
                return this.parameterValuesField;
            }
            set {
                this.parameterValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class UniqueIdentifier {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class ParameterValue {
        
        private UniqueIdentifier uniqueIdentifierField;
        
        private Measurement measurementField;
        
        /// <remarks/>
        public UniqueIdentifier UniqueIdentifier {
            get {
                return this.uniqueIdentifierField;
            }
            set {
                this.uniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class Measurement {
        
        private MeasurementType typeField;
        
        private bool typeFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeasurementType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public enum MeasurementType {
        
        /// <remarks/>
        meter,
        
        /// <remarks/>
        kilogram,
        
        /// <remarks/>
        seconds,
        
        /// <remarks/>
        ampere,
        
        /// <remarks/>
        kelvin,
        
        /// <remarks/>
        candela,
        
        /// <remarks/>
        mole,
        
        /// <remarks/>
        units,
        
        /// <remarks/>
        radians,
        
        /// <remarks/>
        percent,
        
        /// <remarks/>
        boolean,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Messages")]
    public partial class Subscribe {
        
        private UniqueIdentifier entityField;
        
        private UniqueIdentifier observableField;
        
        private UniqueIdentifier subscriberField;
        
        /// <remarks/>
        public UniqueIdentifier Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Observable {
            get {
                return this.observableField;
            }
            set {
                this.observableField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Messages")]
    public partial class Observation {
        
        private UniqueIdentifier entityField;
        
        private UniqueIdentifier observableField;
        
        private long dateField;
        
        private Measurement measurementField;
        
        /// <remarks/>
        public UniqueIdentifier Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Observable {
            get {
                return this.observableField;
            }
            set {
                this.observableField = value;
            }
        }
        
        /// <remarks/>
        public long Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Messages")]
    public partial class Observe {
        
        private UniqueIdentifier entityField;
        
        private UniqueIdentifier observableField;
        
        private UniqueIdentifier observerField;
        
        /// <remarks/>
        public UniqueIdentifier Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Observable {
            get {
                return this.observableField;
            }
            set {
                this.observableField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Observer {
            get {
                return this.observerField;
            }
            set {
                this.observerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Messages")]
    public partial class Deregister {
        
        private UniqueIdentifier registrarField;
        
        private UniqueIdentifier entityField;
        
        /// <remarks/>
        public UniqueIdentifier Registrar {
            get {
                return this.registrarField;
            }
            set {
                this.registrarField = value;
            }
        }
        
        /// <remarks/>
        public UniqueIdentifier Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class Parameter {
        
        private UniqueIdentifier uniqueIdentifierField;
        
        private ParameterDescription descriptionField;
        
        /// <remarks/>
        public UniqueIdentifier UniqueIdentifier {
            get {
                return this.uniqueIdentifierField;
            }
            set {
                this.uniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public ParameterDescription Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class ParameterDescription : SimpleDescription {
        
        private MeasurementType measurementField;
        
        private Measurement minimumField;
        
        private Measurement maximumField;
        
        private Measurement defaultField;
        
        private bool requiredField;
        
        /// <remarks/>
        public MeasurementType Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterDescription))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueDescription))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityDescription))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class SimpleDescription {
        
        private string nameField;
        
        private string remarksField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class ValueDescription : SimpleDescription {
        
        private MeasurementType measurementField;
        
        private Measurement minimumField;
        
        private Measurement maximumField;
        
        private Measurement defaultField;
        
        /// <remarks/>
        public MeasurementType Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
        
        /// <remarks/>
        public Measurement Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class EntityDescription : SimpleDescription {
        
        private string manufacturerField;
        
        private string modelField;
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class Actionable {
        
        private UniqueIdentifier uniqueIdentifierField;
        
        private SimpleDescription descriptionField;
        
        private Parameter[] parametersField;
        
        /// <remarks/>
        public UniqueIdentifier UniqueIdentifier {
            get {
                return this.uniqueIdentifierField;
            }
            set {
                this.uniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public SimpleDescription Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Parameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class Observable {
        
        private UniqueIdentifier uniqueIdentifierField;
        
        private ValueDescription descriptionField;
        
        /// <remarks/>
        public UniqueIdentifier UniqueIdentifier {
            get {
                return this.uniqueIdentifierField;
            }
            set {
                this.uniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public ValueDescription Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Types")]
    public partial class Entity {
        
        private UniqueIdentifier uniqueIdentifierField;
        
        private EntityDescription descriptionField;
        
        private Observable[] observablesField;
        
        private Actionable[] actionablesField;
        
        /// <remarks/>
        public UniqueIdentifier UniqueIdentifier {
            get {
                return this.uniqueIdentifierField;
            }
            set {
                this.uniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public EntityDescription Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Observable[] Observables {
            get {
                return this.observablesField;
            }
            set {
                this.observablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Actionable[] Actionables {
            get {
                return this.actionablesField;
            }
            set {
                this.actionablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bebbs.co.uk/Harmonize/Messages")]
    public partial class Register {
        
        private UniqueIdentifier registrarField;
        
        private Entity entityField;
        
        /// <remarks/>
        public UniqueIdentifier Registrar {
            get {
                return this.registrarField;
            }
            set {
                this.registrarField = value;
            }
        }
        
        /// <remarks/>
        public Entity Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
    }
}
