//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bebbs.Harmonize.With.Owl.Intuition.Tests.Packet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bebbs.Harmonize.With.Owl.Intuition.Tests.Packet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;electricity id=&apos;4437190032EC&apos;&gt;&lt;signal rssi=&apos;-53&apos; lqi=&apos;19&apos;/&gt;&lt;battery level=&apos;100%&apos;/&gt;&lt;chan id=&apos;0&apos;&gt;&lt;curr units=&apos;w&apos;&gt;1352.00&lt;/curr&gt;&lt;day units=&apos;wh&apos;&gt;3308.63&lt;/day&gt;&lt;/chan&gt;&lt;chan id=&apos;1&apos;&gt;&lt;curr units=&apos;w&apos;&gt;0.00&lt;/curr&gt;&lt;day units=&apos;wh&apos;&gt;0.00&lt;/day&gt;&lt;/chan&gt;&lt;chan id=&apos;2&apos;&gt;&lt;curr units=&apos;w&apos;&gt;0.00&lt;/curr&gt;&lt;day units=&apos;wh&apos;&gt;0.00&lt;/day&gt;&lt;/chan&gt;&lt;/electricity&gt;.
        /// </summary>
        internal static string ElectricityPacket {
            get {
                return ResourceManager.GetString("ElectricityPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;wrapper&gt;&lt;electricity id=&apos;4437190032EC&apos;&gt;&lt;signal rssi=&apos;-53&apos; lqi=&apos;19&apos;/&gt;&lt;battery level=&apos;100%&apos;/&gt;&lt;chan id=&apos;0&apos;&gt;&lt;curr units=&apos;w&apos;&gt;1352.00&lt;/curr&gt;&lt;day units=&apos;wh&apos;&gt;3308.63&lt;/day&gt;&lt;/chan&gt;&lt;chan id=&apos;1&apos;&gt;&lt;curr units=&apos;w&apos;&gt;0.00&lt;/curr&gt;&lt;day units=&apos;wh&apos;&gt;0.00&lt;/day&gt;&lt;/chan&gt;&lt;chan id=&apos;2&apos;&gt;&lt;curr units=&apos;w&apos;&gt;0.00&lt;/curr&gt;&lt;day units=&apos;wh&apos;&gt;0.00&lt;/day&gt;&lt;/chan&gt;&lt;/electricity&gt;&lt;/wrapper&gt;.
        /// </summary>
        internal static string WrappedElectricity {
            get {
                return ResourceManager.GetString("WrappedElectricity", resourceCulture);
            }
        }
    }
}
