//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bebbs.Harmonize.With.Owl.Intuition.Tests.Command.Response {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bebbs.Harmonize.With.Owl.Intuition.Tests.Command.Response.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK,DEVICE,0,F2,CMR180,1,0,-53,20,1,178,0,0.0:0,0.00,0,0,0,0.00.
        /// </summary>
        internal static string DeviceResponse {
            get {
                return ResourceManager.GetString("DeviceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK,DEVICE,CMR180,ROOM_STAT,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE.
        /// </summary>
        internal static string RostaResponse {
            get {
                return ResourceManager.GetString("RostaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK,SAVE.
        /// </summary>
        internal static string SaveResponse {
            get {
                return ResourceManager.GetString("SaveResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK,UDP,,192.168.1.27,13.
        /// </summary>
        internal static string UdpResponse {
            get {
                return ResourceManager.GetString("UdpResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK,VERSION,3,1,4.
        /// </summary>
        internal static string VersionResponse {
            get {
                return ResourceManager.GetString("VersionResponse", resourceCulture);
            }
        }
    }
}
